export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const GOOGLE_CLIENT_ID = Symbol('GOOGLE_CLIENT_ID');
export const PASSWORD_RESET_TOKENS_REPOSITORY = Symbol(
  'PASSWORD_RESET_TOKENS_REPOSITORY',
);
export const PASSWORD_RESET_NOTIFIER = Symbol('PASSWORD_RESET_NOTIFIER');
export const REFRESH_TOKENS_REPOSITORY = Symbol('REFRESH_TOKENS_REPOSITORY');
export const EMAIL_VERIFICATION_TOKENS_REPOSITORY = Symbol(
  'EMAIL_VERIFICATION_TOKENS_REPOSITORY',
);
export const EMAIL_VERIFICATION_NOTIFIER = Symbol(
  'EMAIL_VERIFICATION_NOTIFIER',
);
