export const SEBASTIAN_ENTRY_REPOSITORY = Symbol('SEBASTIAN_ENTRY_REPOSITORY');
export const SEBASTIAN_GOAL_REPOSITORY = Symbol('SEBASTIAN_GOAL_REPOSITORY');
export const SEBASTIAN_BADGE_REPOSITORY = Symbol('SEBASTIAN_BADGE_REPOSITORY');
export const TELEGRAM_LINK_REPOSITORY = Symbol('TELEGRAM_LINK_REPOSITORY');
