export const AUDIT_REQUESTS_REPOSITORY = Symbol('AUDIT_REQUESTS_REPOSITORY');
export const AUDIT_AUTOMATION_CONFIG = Symbol('AUDIT_AUTOMATION_CONFIG');
export const AUDIT_QUEUE = Symbol('AUDIT_QUEUE');
export const AUDIT_NOTIFIER = Symbol('AUDIT_NOTIFIER');
export const AUDIT_SELF_GUARD = Symbol('AUDIT_SELF_GUARD');
