export const LEAD_MAGNET_REQUEST_REPOSITORY = Symbol(
  'LEAD_MAGNET_REQUEST_REPOSITORY',
);
export const LEAD_MAGNET_NOTIFIER = Symbol('LEAD_MAGNET_NOTIFIER');
export const TOOLKIT_PDF_GENERATOR = Symbol('TOOLKIT_PDF_GENERATOR');
export const TOOLKIT_CONTENT_ASSEMBLER = Symbol('TOOLKIT_CONTENT_ASSEMBLER');
