export const WEATHER_PROXY = Symbol('WEATHER_PROXY');
export const WEATHER_PREFERENCES_REPOSITORY = Symbol(
  'WEATHER_PREFERENCES_REPOSITORY',
);
export const OPENWEATHERMAP_API_KEY = Symbol('OPENWEATHERMAP_API_KEY');
export const OPENWEATHERMAP_PROXY = Symbol('OPENWEATHERMAP_PROXY');
