export const SESSIONS_REPOSITORY = Symbol('SESSIONS_REPOSITORY');
export const PARTICIPANTS_REPOSITORY = Symbol('PARTICIPANTS_REPOSITORY');
export const ANSWERS_REPOSITORY = Symbol('ANSWERS_REPOSITORY');
export const MASTERY_REPOSITORY = Symbol('MASTERY_REPOSITORY');
export const INCIDENTS_REPOSITORY = Symbol('INCIDENTS_REPOSITORY');
export const FORMATION_MAILER = Symbol('FORMATION_MAILER');
export const SESSION_STATE_CACHE = Symbol('SESSION_STATE_CACHE');
