export const SESSIONS_REPOSITORY = Symbol('SESSIONS_REPOSITORY');
export const PARTICIPANTS_REPOSITORY = Symbol('PARTICIPANTS_REPOSITORY');
export const ANSWERS_REPOSITORY = Symbol('ANSWERS_REPOSITORY');
export const MASTERY_REPOSITORY = Symbol('MASTERY_REPOSITORY');
export const INCIDENTS_REPOSITORY = Symbol('INCIDENTS_REPOSITORY');
export const FORMATION_MAILER = Symbol('FORMATION_MAILER');
export const SESSION_STATE_CACHE = Symbol('SESSION_STATE_CACHE');
export const STREAM_CAPACITY = Symbol('STREAM_CAPACITY');
export const CATALOGUE_COURS = Symbol('CATALOGUE_COURS');
export const FREE_RESPONSES_REPOSITORY = Symbol('FREE_RESPONSES_REPOSITORY');
export const TEACHER_ANNOTATIONS_REPOSITORY = Symbol(
  'TEACHER_ANNOTATIONS_REPOSITORY',
);
export const FORMATION_GROUPS_REPOSITORY = Symbol(
  'FORMATION_GROUPS_REPOSITORY',
);
export const SCORES_REPOSITORY = Symbol('SCORES_REPOSITORY');
export const ESCAPE_REPOSITORY = Symbol('ESCAPE_REPOSITORY');
