export const NEWSLETTER_SUBSCRIBER_REPOSITORY = Symbol(
  'NEWSLETTER_SUBSCRIBER_REPOSITORY',
);
export const NEWSLETTER_MAILER = Symbol('NEWSLETTER_MAILER');
export const EMAIL_DRIP_SCHEDULER = Symbol('EMAIL_DRIP_SCHEDULER');
