export const BUDGET_GROUP_REPOSITORY = Symbol('BUDGET_GROUP_REPOSITORY');
export const BUDGET_CATEGORY_REPOSITORY = Symbol('BUDGET_CATEGORY_REPOSITORY');
export const BUDGET_ENTRY_REPOSITORY = Symbol('BUDGET_ENTRY_REPOSITORY');
export const BUDGET_SHARE_NOTIFIER = Symbol('BUDGET_SHARE_NOTIFIER');
export const BUDGET_SHARE_ATTEMPT_REPOSITORY = Symbol(
  'BUDGET_SHARE_ATTEMPT_REPOSITORY',
);
export const RECURRING_ENTRY_REPOSITORY = Symbol('RECURRING_ENTRY_REPOSITORY');
export const BUDGET_PDF_RENDERER = Symbol('BUDGET_PDF_RENDERER');
export const CATEGORY_INFERENCE_STRATEGY = Symbol(
  'CATEGORY_INFERENCE_STRATEGY',
);
export const BUDGET_MEMBER_CONTRIBUTION_REPOSITORY = Symbol(
  'BUDGET_MEMBER_CONTRIBUTION_REPOSITORY',
);
export const BUDGET_GOAL_REPOSITORY = Symbol('BUDGET_GOAL_REPOSITORY');
