export const BUDGET_GROUP_REPOSITORY = Symbol('BUDGET_GROUP_REPOSITORY');
export const BUDGET_CATEGORY_REPOSITORY = Symbol('BUDGET_CATEGORY_REPOSITORY');
export const BUDGET_ENTRY_REPOSITORY = Symbol('BUDGET_ENTRY_REPOSITORY');
export const BUDGET_SHARE_NOTIFIER = Symbol('BUDGET_SHARE_NOTIFIER');
export const RECURRING_ENTRY_REPOSITORY = Symbol('RECURRING_ENTRY_REPOSITORY');
